#!/bin/bash

function exit_on_error { echo "$@" ; exit 1 ; }

# TODO: use $1 to do -v $1
# TODO: add --nobump

# all opts go to ./gvn
echo bumping version number
gvn "$@"  || exit_on_error problem with gvn bump 


# get version number
gvnVersion=$(sed -e 's/^.*"v/v/' -e 's/".*//'  < gvnVersion.*)


# commit all files
echo new version: ${gvnVersion}. Enter commit and tag message....
read message
git commit -m "${message}" -a  || exit_on_error problem with git commit 


# get that commit hash; e.g.
#eeaebea  (HEAD -> master, origin/master)       # you cant see tag yet
commitID=$(git log -1 --pretty="%h %d" | awk '{ print $1 }')
[ x${commitID} == "x" ] && exit_on_error cant get commitID 


# make tag on that commit
echo going to tag commit ${commitID}, ok\?
read ok
git tag -a $gvnVersion -m "${message}" ${commitID} || exit_on_error git tag error ${gvnVersion} ${commitID}


# push files  and tags (see config)
echo going to push all, ok\?
read ok
git push --follow-tags  || exit_on_error  problem with push --follow-tags


echo
echo done...
git log -1 --pretty="%h %d %s" --decorate=full                   # look at what you've done

